# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5e404b1e1521f1f1b6fe179d1b5a22805105195e6f5d1d94d4e86972fb7f66d635711eadf763dc04ed8ecbccc323198fddddfdd9495e4ad13cf6b1b61ff2f02

test:
  secret_key_base: 91024cb7e4fe41294d4392cfd6c9d2bd97ee0d17ff9ab8856cf7f3b7638e1c0bd821e7b217b1a816b21e7720d1e36e8947480f8348333210e950847a8fb182d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
